### ISSUE TITLE
Support for Bcast, Allgatherv of TL_NCCL

### ISSUE THREAD

**Issue by bellenlau** [openucx/ucc#1187]
Dear staff,

does UCC support TL_NCCL for Allgatherv or Bcast? nsys traces of MPI collectives with UCC v1.5.0 suggest that the NCCL backend is supported only for Allreduce operations. These envs:

```
export OMPI_MCA_coll_ucc_enable=1
export OMPI_MCA_coll_ucc_priority=100
export UCC_TL_NCCL_TUNE=bcast:cuda:inf
```

are used to activate the TL.

By using the DEBUG env, for the Bcast for example I see:

```
[1757659088.030559] [lrdn0964:2337347:0] ucc_coll_score_map.c:140  UCC  DEBUG coll Bcast is not supported for TL_NCCL, fallback TL_UCP
```
As long as in the source code there is also the "not implemented" option, it is not clear if the lack of support for this case depends on some feature of BCAST APIs in my code (datatype, dimension of the buffer,algoritm?)

UPDATE: There is another error message before the above-mentioned one:
```
[1757660377.339382] [lrdn0003:2247201:0]    tl_nccl_team.c:177  TL_NCCL DEBUG NCCL error 5 invalid usage (run with NCCL_DEBUG=WARN for details)
 ```
which seem to be related to the fact that it is trying to initialize multiple ranks on the same GPU. Not clear why TL_NCCL works with Allreduce and not with Bcast?

**Comment by bellenlau** [comment]
The issue was that in this reproducer the gpu device per mpi task was not explicitely set and the mapping was left to slurm. Apparently for the bcast this was not enough, while for the allreduce it is. By using an explicit GPU-MPI mapping in the source code it worked, and I can see ncclbcast in nsys profile.

It might be hepful to add a less hidden warning.

**Comment by Sergei-Lebedev** [comment]
Allreduce shouldn't work if GPU devices are not set as well. Also NCCL has other limitations when using it MPI env, see https://github.com/openucx/ucc/issues/106

**Comment by bellenlau** [comment]
Hello Sergei, thank you for your reply. Indeed, in a toy code the proper mapping of the mpi task to a gpu was enough to use NCCL backend. Unfortunately, the behaviour is still unclear, as I compiled a real application with OpenMPI/5.0.7 and activated NCCL backend for allgatherv, but I still see that only BCAST and Allreduce use NCCL. 

By tracing nvtx and mpi with nsys I get the following:

nvtx summary

```
Time	Total Time	Instances	Avg	Med	Min	Max	StdDev	Range
61.0%	934,662 ms	1	934,662 ms	934,662 ms	934,662 ms	934,662 ms	0 ns	NCCL:ncclCommInitRankConfig
32.0%	487,706 ms	1	487,706 ms	487,706 ms	487,706 ms	487,706 ms	0 ns	NCCL:ncclCommDestroy
5.0%	83,891 ms	100	838,908 μs	14,445 μs	5,705 μs	82,580 ms	8,257 ms	NCCL:ncclBroadcast
0.0%	12,333 ms	1884	6,546 μs	6,125 μs	5,642 μs	36,330 μs	1,962 μs	NCCL:ncclAllReduce
0.0%	149,204 μs	1	149,204 μs	149,204 μs	149,204 μs	149,204 μs	0 ns	NCCL:ncclCommFinalize
```

mpi summary

```
Time	Total Time	Instances	Avg	Med	Min	Max	StdDev	Source	Name
61.0%	15,971 s	94	169,903 ms	16,315 ms	98,057 μs	872,236 ms	282,127 ms	collectives	MPI_Allgatherv
18.0%	4,811 s	1	4,811 s	4,811 s	4,811 s	4,811 s	0 ns	other	MPI_Init_thread
11.0%	2,993 s	1102	2,716 ms	1,299 μs	143 ns	855,617 ms	27,457 ms	collectives	MPI_Barrier
4.0%	1,095 s	1205	908,971 μs	967 ns	150 ns	1,035 s	29,816 ms	collectives	MPI_Bcast
1.0%	466,838 ms	102	4,577 ms	2,201 ms	1,817 ms	25,560 ms	5,635 ms	collectives	MPI_Gatherv
1.0%	459,550 ms	2079	221,043 μs	192,425 μs	808 ns	40,076 ms	947,455 μs	collectives	MPI_Allreduce
0.0%	106,675 ms	1	106,675 ms	106,675 ms	106,675 ms	106,675 ms	0 ns	other	MPI_Finalize
```

Here I am running with 4 gpus/mpi task, the application binds each mpi task to a different gpu, communications do not overlap and all of them use a communicator which is equivalent to the MPI_COMM_WORLD.

I am running with these envs to use UCC and NCCL backend

```
export OMPI_MCA_coll_ucc_enable=1
export OMPI_MCA_coll_ucc_priority=100
export UCC_TL_NCCL_TUNE=allgatherv:cuda:inf

```

Also the trace show taht MPI_Allgatherv do not use a NCCL backend (differently from Allreduce for example in this picture)

<img width="1439" height="414" alt="Image" src="https://github.com/user-attachments/assets/a563051b-934c-4483-b57e-e4f0235e581a" />

**Comment by Sergei-Lebedev** [comment]
Hello Laura, could you please rerun with UCC_LOG_LEVEL=debug and share log file?

**Comment by bellenlau** [comment]
Dear Sergei, 
please find it attached.

[log_ucc_nccl.txt](https://github.com/user-attachments/files/22357500/log_ucc_nccl.txt)

Thank you,

Laura

**Comment by Sergei-Lebedev** [comment]
Hello Laura, thanks for sharing the log file. From it I can see that NCCL was correctly initialized and selected for allgatherv. For example here
```
[1758005591.525627] [lrdn1532:379402:0] ucc_coll_score_map.c:225  UCC  INFO  Allgatherv:
[1758005591.525627] [lrdn1532:379402:0] ucc_coll_score_map.c:225  UCC  INFO  	Host: {0..inf}:TL_UCP:10=ucc_tl_ucp_allgatherv_ring_init 
[1758005591.525627] [lrdn1532:379402:0] ucc_coll_score_map.c:225  UCC  INFO  	Cuda: {0..16383}:TL_NCCL:10=ucc_tl_nccl_coll_init {16K..1048575}:TL_NCCL:10=ucc_tl_nccl_coll_init {1M..inf}:TL_NCCL:10=ucc_tl_nccl_coll_init 
[1758005591.525627] [lrdn1532:379402:0] ucc_coll_score_map.c:225  UCC  INFO  	CudaManaged: {0..inf}:TL_NCCL:10=ucc_tl_nccl_allgatherv_p2p_init 
```
Here you can also see msg ranges:
```
{0..16383}:TL_NCCL:10=ucc_tl_nccl_coll_init
{16K..1048575}:TL_NCCL:10=ucc_tl_nccl_coll_init
{1M..inf}:TL_NCCL:10=ucc_tl_nccl_coll_init 
```

Since NCCL library doesn't have native allgatherv implementation we provide some variants in UCC that are built on top of other NCCL operations. In particular there are 3 allgatherv algorithms that are used for a specific msg sizes.

By default we use
"allgatherv based on nccl point-to-point" for allgatherv in {0..16383}
"allgatherv with buffered copy" for allgatherv in {16K..1048575}
"allgatherv based on nccl bcast" for allgatherv in {1M..inf}
If allgatherv in your application falls into last category, i.e. allgatherv size >= 1Mb then UCC will use NCCL bcast to emulate allgatherv. It might explain why you see only bcast in nsys.

To verify this, you can manually overwrite default UCC thresholds and use another algorithm. For example 
``UCC_TL_NCCL_TUNE=allgatherv:cuda:inf:@bcopy.`` With this variable I expect to see NCCL allgather calls in nsys output.

**Comment by bellenlau** [comment]
Thank you for the information. Unfortuntely also by selecting the bcopy algorithm I don't see a NCCL backend in the trace of MPI Allgatherv, as in this case:

<img width="1539" height="837" alt="Image" src="https://github.com/user-attachments/assets/734a0cb1-52ea-471e-9877-073423faeef1" />

The summary shows that the MPI message sizes are of the order of hundreds of MB on average, the one in the picture is tens of MB of total message size sent/recv. I have checked also the other Allgatherv calls and behave in the same way. However, the logfile show that the algorithm is the one selected with the environment variable:

```
[1758014743.637271] [lrdn0369:1398114:0] ucc_coll_score_map.c:225  UCC  INFO  Allgatherv:
[1758014743.637271] [lrdn0369:1398114:0] ucc_coll_score_map.c:225  UCC  INFO    Host: {0..inf}:TL_UCP:10=ucc_tl_ucp_allgatherv_ring_init
[1758014743.637271] [lrdn0369:1398114:0] ucc_coll_score_map.c:225  UCC  INFO    Cuda: {0..16383}:TL_NCCL:10=ucc_tl_nccl_allgatherv_bcopy_init {16K..1048575}:TL_NCCL:10=ucc_tl_nccl_allgatherv_bcopy_init {1M..inf}:TL_NCCL:10=ucc_tl_nccl_allgatherv_bcopy_init
[1758014743.637271] [lrdn0369:1398114:0] ucc_coll_score_map.c:225  UCC  INFO    CudaManaged: {0..inf}:TL_NCCL:10=ucc_tl_nccl_allgatherv_p2p_init
```

By inspecting the callstack it seems that the MPI_Allgatherv does not use libucc, differently from Bcast/Allreduce calls:

here the callstack from sampling point of the Allgatherv

<img width="1524" height="720" alt="Image" src="https://github.com/user-attachments/assets/cc9c0835-948a-4fcd-8f31-36674784bda1" />

here the callstack from sampling point of the Allreduce

<img width="1477" height="503" alt="Image" src="https://github.com/user-attachments/assets/f0e7f78d-ec68-4eb5-a472-166697522190" />

while in the reproducer where I could see the NCCL calls also for Allgatherv from the call stack it seems that the p2p algorithm is used (which surprised me because we are not using cudamanaged?):

<img width="1512" height="530" alt="Image" src="https://github.com/user-attachments/assets/100923b9-43fb-4cf5-804f-973d8381ffdc" />

Both in the reproducer and the code the buffer is allocated on GPU with OpenACC, but there are a couple of differences:

- in the code, MPI_Allgatherv are in place
- in the reproducer the MPI_Allgatherv are directly wrapped with `!$acc host_data use_device` directive, while in the code the buffer is allocated on the GPU with OpenACC, passed to a subroutine as a device variable via ` !$acc host_data use_device`, and inside the MPI_Allgatherv has as an input a variable declared as device variable.

**Comment by Sergei-Lebedev** [comment]
Allgatherv backtrace indeed shows that UCC is not used for allgatherv, but it first tries to use UCC allgatherv and then fallbacks to another MPI coll component, this is implemented here (https://github.com/open-mpi/ompi/blob/9be4387d5faa8bd66bf7269adbd4c4fcf740a7be/ompi/mca/coll/ucc/coll_ucc_allgatherv.c#L80).
This might happen because datatype is not supported by UCC or no UCC backends support given combination of datatype and memory type or some internal erorr.

Maybe we first rule out datatype? You can see additional messages from ompi (including unsupported datatype) by adding ``--mca coll_ucc_verbose 10`` to mpirun.

**Comment by bellenlau** [comment]
Thank you, it is very informative. Yes, the datatype is not supported:

```
[lrdn0257.leonardo.local:2017789] coll_ucc_allgatherv.c:80 - mca_coll_ucc_allgatherv() running fallback allgatherv
[lrdn0257.leonardo.local:2017786] coll_ucc_allgatherv.c:71 - mca_coll_ucc_allgatherv() running ucc allgatherv
[lrdn0257.leonardo.local:2017786] coll_ucc_allgatherv.c:28 - mca_coll_ucc_allgatherv_init() ompi_datatype is not supported: dtype = OPAL_EMPTY

```

Another relevant difference between the code and the reproducer is that the code uses a custom mpi datatype created with mpi_type_create_subarray.

**Comment by bellenlau** [comment]
Hello, using a non custom mpi datatype enabled UCC also for allgatherv. However I noticed that if I use MPI_DATATYPE_NULL in the MPI_Allgatherv in place, as here:
```
CALL MPI_ALLGATHERV(MPI_IN_PLACE, 0, MPI_DATATYPE_NULL, hpsi, recv_counts, displs, MPI_DOUBLE_COMPLEX, inter_bgrp_comm, ierr`
```
the allgatherv does not use ucc, while this
```
CALL MPI_ALLGATHERV(MPI_IN_PLACE, 0, MPI_DOUBLE_COMPLEX, spsi, recv_counts, displs, MPI_DOUBLE_COMPLEX, inter_bgrp_comm, ierr)
```
uses UCC.

The logfile warns about no support for the first case

```
[lrdn1965.leonardo.local:2616117] coll_ucc_allgatherv.c:28 - mca_coll_ucc_allgatherv_init() ompi_datatype is not supported: dtype = OPAL_EMPTY
[lrdn1965.leonardo.local:2616117] coll_ucc_allgatherv.c:80 - mca_coll_ucc_allgatherv() running fallback allgatherv
[lrdn1965.leonardo.local:2616122] coll_ucc_allgatherv.c:71 - mca_coll_ucc_allgatherv() running ucc allgatherv
[lrdn1965.leonardo.local:2616122] coll_ucc_allgatherv.c:28 - mca_coll_ucc_allgatherv_init() ompi_datatype is not supported: dtype = OPAL_EMPTY
[lrdn1965.leonardo.local:2616122] coll_ucc_allgatherv.c:80 - mca_coll_ucc_allgatherv() running fallback allgatherv
[lrdn1965.leonardo.local:2616110] coll_ucc_allgatherv.c:71 - mca_coll_ucc_allgatherv() running ucc allgatherv
[lrdn1965.leonardo.local:2616110] coll_ucc_allgatherv.c:28 - mca_coll_ucc_allgatherv_init() ompi_datatype is not supported: dtype = OPAL_EMPTY
[lrdn1965.leonardo.local:2616110] coll_ucc_allgatherv.c:80 - mca_coll_ucc_allgatherv() running fallback allgatherv
[lrdn1965.leonardo.local:2616112] coll_ucc_allgatherv.c:71 - mca_coll_ucc_allgatherv() running ucc allgatherv
[lrdn1965.leonardo.local:2616112] coll_ucc_allgatherv.c:28 - mca_coll_ucc_allgatherv_init() ompi_datatype is not supported: dtype = OPAL_EMPTY
[lrdn1965.leonardo.local:2616112] coll_ucc_allgatherv.c:80 - mca_coll_ucc_allgatherv() running fallback allgatherv
[lrdn1965.leonardo.local:2616117] coll_ucc_allgatherv.c:71 - mca_coll_ucc_allgatherv() running ucc allgatherv
[lrdn1965.leonardo.local:2616112] coll_ucc_allgatherv.c:71 - mca_coll_ucc_allgatherv() running ucc allgatherv
[lrdn1965.leonardo.local:2616122] coll_ucc_allgatherv.c:71 - mca_coll_ucc_allgatherv() running ucc allgatherv
[lrdn1965.leonardo.local:2616110] coll_ucc_allgatherv.c:71 - mca_coll_ucc_allgatherv() running ucc allgatherv

```
Is it expected that for an in-place mpi_allgatherv the datatype checked for the conversion is the one of the sended buffer?

**Comment by Sergei-Lebedev** [comment]
It is a bug fixed in ompi 5.0.8 https://github.com/open-mpi/ompi/pull/13224
